### ISSUE TITLE
jsHint or JSCS is linting library (fusioncharts)

### ISSUE THREAD

**Issue by lawrence1949** [taylor1791/front-end-work-flow#3]
In my gulp file line 76:
browser: [ 'app//*.js', '!app/lib//.js', '!app//.test.js' ]

This will exclude fusionchart from linting. But I lost it when I run the build task --- cyclops-crush.

If I remove the the library from this line:
browser: [ 'app//_.js', '!app//_.test.js' ]
It will be included when I ran cyclops-crush, but jsHint or JSCS is also linting the library, which makes the application extremely slow.

**Comment by taylor1791** [comment]
I made the jshint, jscs, json-validate, and html-validate tasks remove libraries from their parsing. Something like the following should fix it. Can you tell me if the following works after updating?

libraries: {
  '/lib': 'app/lib/'
}

**Comment by lawrence1949** [comment]
Looks like it's working now.
